name: IPTV PRO Auto Engine

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install ffmpeg -y

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run IPTV Engine
        run: python processor.py

      - name: Commit output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output.m3u stats.txt

          git diff --cached --quiet || (
            git commit -m "PRO IPTV auto update"
            git push
          )
